force-app/commons/triggerHandler/objects/TriggerFieldDefault__mdt/TriggerFieldDefault__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Field Default</label>
    <pluralLabel>Trigger Field Defaults</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerFieldDefault__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Order of field population. May be left blank if irrelevant.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/TriggerLogic__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Logic</label>
    <pluralLabel>Trigger Logics</pluralLabel>
</CustomObject>

force-app/commons/triggerHandlerMdt/objects/TriggerLogic__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>TriggerLogic</relationshipLabel>
    <relationshipName>TriggerLogic</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE_INSERT</fullName>
                <default>true</default>
                <label>BEFORE_INSERT</label>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerValidationRule__mdt/TriggerValidationRule__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Validation Rule</label>
    <pluralLabel>Trigger Validation Rules</pluralLabel>
</CustomObject>

force-app/commons/triggerHandler/objects/TriggerValidationRule__mdt/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <inlineHelpText>When this validation should be run.</inlineHelpText>
    <label>Trigger</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE_INSERT</fullName>
                <default>true</default>
                <label>BEFORE_INSERT</label>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/commons/triggerHandler/classes/MetadataDefinedTriggerClasses.cls
/**
 * This class is responsible for querying custom metadata (TriggerValidationRule__mdt, TriggerLogic__mdt or TriggerFieldDefault__mdt)
 * and creating instances of classes defined in ApexClass__c field.
 */
public with sharing class MetadataDefinedTriggerClasses {
    @TestVisible private static List<SObject> mockResponse;

    /**
     * @param customMetadata Type of custom metadata to query TriggerValidationRule__mdt/TriggerLogic__mdt/TriggerFieldDefault__mdt
     * @param tc Current Trigger Context
     * @param instances Empty list of desired result type ex. `new List<TriggerValidationRule> ()`
     *
     * @return New instances of classes defined in ApexClass__c field of the custom metadata.
     * @throws TypeException if Type.newInstance() failed.
     */
    public static List<Object> getInstances(SObjectType customMetadata, TriggerContext tc, List<Object> instances) {
        for (SObject setting : getCustomMetadataRecords(customMetadata, String.valueOf(tc.sObjectType), tc.operationType.name())) {
            try {
                Type ruleClass = Type.forName((String) setting.get('ApexClass__c'));
                instances.add(ruleClass.newInstance());

            } catch (Exception ex) {
                throw new TypeException('Apex class defined in custom metadata "' +
                        customMetadata + '.' + setting.get('DeveloperName') + '"' +
                        ' is invalid. Please check if corresponding class is public and implements correct interface.'
                );
            }
        }

        return instances;
    }

    private static List<SObject> getCustomMetadataRecords(SObjectType customMetadata, String sObjectType, String triggerOperation) {
        if (mockResponse != null) {
            return mockResponse;

        } else {
            return Database.query(
                    'SELECT ApexClass__c, DeveloperName'
                            + ' FROM ' + customMetadata
                            + ' WHERE IsEnabled__c = TRUE'
                            + ' AND SObject__c = :sObjectType'
                            + ' AND Trigger__c = :triggerOperation'
                            + ' ORDER BY Order__c NULLS LAST'
            );
        }
    }
}