force-app/commons/triggerHandler/objects/TriggerFieldDefault__mdt/TriggerFieldDefault__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Field Default</label>
    <pluralLabel>Trigger Field Defaults</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerFieldDefault__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Order of field population. May be left blank if irrelevant.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/TriggerLogic__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Logic</label>
    <pluralLabel>Trigger Logics</pluralLabel>
</CustomObject>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/AfterDelete__c.field-meta.xml
<CustomField>
    <fullName>AfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/AfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>AfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/AfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>AfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/BeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>BeforeDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>BeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/BeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>BeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerLogic__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerLogic__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>TriggerLogic</relationshipLabel>
    <relationshipName>TriggerLogic</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerLogic__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Depending on the selected value, Apex class should implement following interface:
Field Default - TriggerFieldDefault
Validation Rule - TriggerValidationRule
Logic - TriggerLogic</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Default</fullName>
                <default>true</default>
                <label>Field Default</label>
            </value>
            <value>
                <fullName>Validation Rule</fullName>
            </value>
            <value>
                <fullName>Logic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerValidationRule__mdt/TriggerValidationRule__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Validation Rule</label>
    <pluralLabel>Trigger Validation Rules</pluralLabel>
</CustomObject>

force-app/commons/triggerHandler/classes/TriggerLogicSelector.cls
/**
* MIT License
*
* Copyright (c) 2019 Piotr Kożuchowski
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

/**
 * This class is responsible for querying custom metadata (TriggerLogic__mdt)
 * and creating instances of classes defined in ApexClass__c field.
 */
public with sharing class TriggerLogicSelector {
    @TestVisible static List<TriggerLogic__mdt> mockMetadata;

    /**
     * @param tc Trigger Context of running trigger
     * @return Trigger Validation Rules for currently executing trigger
     */
    public List<TriggerHandler.ValidationRule> getValidationRules(TriggerContext tc) {
        return (List<TriggerHandler.ValidationRule>) getInstances('Validation Rule', tc, new List<TriggerHandler.ValidationRule>());
    }

    /**
     * @param tc Trigger Context of running trigger
     * @return Trigger Field Defaults for currently executing trigger
     */
    public List<TriggerHandler.FieldDefault> getFieldDefault(TriggerContext tc) {
        return (List<TriggerHandler.FieldDefault>) getInstances('Field Default', tc, new List<TriggerHandler.FieldDefault>());
    }

    /**
     * @param tc Trigger Context of running trigger
     * @return Trigger Logic for currently executing trigger
     */
    public List<TriggerHandler.Logic> getLogic(TriggerContext tc) {
        return (List<TriggerHandler.Logic>) getInstances('Logic', tc, new List<TriggerHandler.Logic>());
    }

    /**
     * @param tc Trigger Context of running trigger
     * @return Trigger Logic for currently executing trigger
     */
    public List<TriggerHandler.AsyncLogic> getAsyncLogic(TriggerContext tc) {
        return (List<TriggerHandler.AsyncLogic>) getInstances('Async Logic', tc, new List<TriggerHandler.AsyncLogic>());
    }


    /**
     * @param customMetadata Type of custom metadata to query TriggerValidationRule__mdt/TriggerLogic__mdt/TriggerFieldDefault__mdt
     * @param tc Current Trigger Context
     * @param instances Empty list of desired result type ex. `new List<TriggerValidationRule> ()`
     *
     * @return New instances of classes defined in ApexClass__c field of the custom metadata.
     * @throws TypeException if Type.newInstance() failed.
     */
    private List<Object> getInstances(String logicType, TriggerContext tc, List<Object> instances) {
        for (TriggerLogic__mdt setting : getCustomMetadataRecords(logicType, String.valueOf(tc.sObjectType), tc.operationType)) {
            try {
                Type ruleClass = Type.forName(setting.ApexClass__c);
                instances.add(ruleClass.newInstance());

            } catch (Exception ex) {
                System.debug('ex: ' + ex);
                throw new TypeException('Apex class defined in custom metadata TriggerLogic__mdt.' + setting.DeveloperName
                        + ' (' + setting.ApexClass__c + ') is invalid. Please check if corresponding class is public and implements correct interface.'
                );
            }
        }

        return instances;
    }

    private List<TriggerLogic__mdt> getCustomMetadataRecords(String type, String sObjectType, TriggerOperation op) {
        SObjectField triggerField = new Map<TriggerOperation, SObjectField>{
                TriggerOperation.BEFORE_INSERT => TriggerLogic__mdt.BeforeInsert__c,
                TriggerOperation.BEFORE_UPDATE => TriggerLogic__mdt.BeforeUpdate__c,
                TriggerOperation.BEFORE_DELETE => TriggerLogic__mdt.BeforeDelete__c,
                TriggerOperation.AFTER_INSERT => TriggerLogic__mdt.AfterInsert__c,
                TriggerOperation.AFTER_UPDATE => TriggerLogic__mdt.AfterUpdate__c,
                TriggerOperation.AFTER_DELETE => TriggerLogic__mdt.AfterDelete__c,
                TriggerOperation.AFTER_UNDELETE => TriggerLogic__mdt.AfterUndelete__c
        }.get(op);

        if (mockMetadata == null) {
            return Database.query('SELECT ApexClass__c, DeveloperName'
                    + ' FROM TriggerLogic__mdt'
                    + ' WHERE Enabled__c = TRUE'
                    + ' AND SObject__c = :sObjectType'
                    + ' AND Type__c =:type'
                    + ' AND ' + triggerField + ' = TRUE'
                    + ' ORDER BY Order__c ASC NULLS LAST, ApexClass__c ASC'
            );
        } else {
            List<TriggerLogic__mdt> settings = new List<TriggerLogic__mdt>();

            for (TriggerLogic__mdt logic : mockMetadata) {
                if (logic.Enabled__c = true
                        && logic.SObject__c == sObjectType
                        && logic.get(triggerField) == true
                        && logic.Type__c == type) {
                    settings.add(logic);
                }
            }

            return settings;
        }
    }
}