force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/HttpCalloutMock__mdt.object-meta.xml
<CustomObject>
    <label>Http Callout Mock</label>
    <pluralLabel>Http Callout Mocks</pluralLabel>
</CustomObject>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText>Name of Apex Class implementing HttpCalloutMock interface that produces response. Alternative to Response__c &amp; StaticResource__c. Class  must be public and have public no-args constructor.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/ApexClassNamespace__c.field-meta.xml
<CustomField>
    <fullName>ApexClassNamespace__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Apex Class Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <inlineHelpText>Specify header per line, in following format:
HeaderName: HeaderValue

ex. 
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Wed, 10 Jul 2024 17:06:24 GMT
Connection: close
Content-Length: 41</inlineHelpText>
    <label>Headers</label>
    <type>TextArea</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <inlineHelpText>Source of the Http Response - Plain Response Body, Apex class name or Static Resource Name.</inlineHelpText>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/StaticResource__c.field-meta.xml
<CustomField>
    <fullName>StaticResource__c</fullName>
    <inlineHelpText>Alternative ot Response__c. If this is provided with Static Resource name, it&apos;s body will be used as response.</inlineHelpText>
    <label>Static Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status Code</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/commons/httpMocks/classes/HttpMocksConfig.cls
/**
* SPDX-License-Identifier: MIT
* Copyright 2023 Piotr Kożuchowski
* apexlibra.org
*/

/**
 * Configuration class for managing HTTP callout mocks defined in custom metadata.
 * Provides access to HttpCalloutMock__mdt records for testing HTTP integrations.
 */
public with sharing class HttpMocksConfig {
    private static Map<String, HttpCalloutMock__mdt> mocks = HttpCalloutMock__mdt.getAll();
    private static Boolean isMocked = false;

    /**
     * Returns all configured HTTP callout mock metadata records.
     * @return List of all HttpCalloutMock__mdt records
     */
    public static List<HttpCalloutMock__mdt> getMocks() {
        return mocks.values();
    }

    /**
     * Retrieves a specific HTTP callout mock by developer name.
     * If the Response__c field exceeds 255 characters, queries the full record to avoid Salesforce's text truncation.
     * @param developerName The developer name of the HttpCalloutMock__mdt record
     * @return The HttpCalloutMock__mdt record with complete response data
     */
    public static HttpCalloutMock__mdt getResponse(String developerName) {
        HttpCalloutMock__mdt mock = mocks.get(developerName);

        if (isMocked || mock.Response__c.length() < 255) {
            return mock;

        } else {
            //Salesforce trims long texts to 255
            return [
                SELECT DeveloperName, ApexClass__c, ApexClassNamespace__c,
                    Status__c, StatusCode__c, Response__c,
                    StaticResource__c, Headers__c
                FROM HttpCalloutMock__mdt
                WHERE DeveloperName = :developerName
                WITH USER_MODE
            ];
        }
    }

    /**
     * Mocks custom metadata records in tests.
     */
    @TestVisible static void mock(List<HttpCalloutMock__mdt> mocks) {
        Map<String, HttpCalloutMock__mdt> mocksMap = new Map<String, HttpCalloutMock__mdt>();
        for (HttpCalloutMock__mdt mock : mocks) {
            mocksMap.put(mock.DeveloperName, mock);
        }
        HttpMocksConfig.mocks = mocksMap;
        HttpMocksConfig.isMocked = true;
    }
}