force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/HttpCalloutMock__mdt.object-meta.xml
<CustomObject>
    <label>Http Callout Mock</label>
    <pluralLabel>Http Callout Mocks</pluralLabel>
</CustomObject>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Default mocks are loaded in the router, while all non-defaults can be used to override default mock in unit tests.</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <inlineHelpText>Regexp pattern for endpoint. It can contain variables denoted by double curly braces. 
Make sure it matches different URL parameters.</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/commons/httpMocks/objects/HttpCalloutMock__mdt/fields/Methods__c.field-meta.xml
<CustomField>
    <fullName>Methods__c</fullName>
    <inlineHelpText>Comma separated methods to match - ex. &quot;GET,POST&quot;</inlineHelpText>
    <label>Methods</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/commons/httpMocks/classes/HttpMocksConfigRouter.cls
/**
* SPDX-License-Identifier: MIT
* Copyright 2023 Piotr Kożuchowski
* apexlibra.org
*/

/**
 * Configuration class for managing HTTP callout mocks defined in custom metadata.
 * Provides access to HttpCalloutMock__mdt records for testing HTTP integrations.
 */
public with sharing class HttpMocksConfigRouter extends HttpCalloutMockRouter {
    private static Map<String, HttpCalloutMock__mdt> mocks = HttpCalloutMock__mdt.getAll();

    /**
     * @return Loads Mocks from custom metadata
     */
    public HttpMocksConfigRouter() {
        for (HttpCalloutMock__mdt mockMdt : mocks.values()) {
            if (mockMdt.Default__c) {
                mock(
                    mockMdt.DeveloperName,
                    mockMdt.Methods__c,
                    mockMdt.Endpoint__c,
                    HttpMocks.config(mockMdt)
                );
            }
        }
    }

    public static HttpCalloutMock__mdt getMock(String name) {
        return mocks.get(name);
    }

    /**
     * Mocks custom metadata records in tests.
     */
    @TestVisible static void mock(List<HttpCalloutMock__mdt> mocks) {
        Map<String, HttpCalloutMock__mdt> mocksMap = new Map<String, HttpCalloutMock__mdt>();
        for (HttpCalloutMock__mdt mock : mocks) {
            mocksMap.put(mock.DeveloperName, mock);
        }
        HttpMocksConfigRouter.mocks = mocksMap;
    }
}