force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/TriggerAction__mdt.object-meta.xml
<CustomObject>
    <description>Configure which apex classes should be run in trigger to process records.
Apex classes should be public and implement MetadataTriggerHandler.Logic interface.</description>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Action</pluralLabel>
</CustomObject>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText>Name of public Apex Class implementing FieldDefaultRule interface.
Inner class can be referenced as well ex. &quot;AccountFieldDefaults.NameDefault&quot;, but both inner and outer class have to be public.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/BypassPermission__c.field-meta.xml
<CustomField>
    <fullName>BypassPermission__c</fullName>
    <inlineHelpText>Custom Permission API name that bypasses action execution. Users with this permission will skip the action logic. Commonly used for integration users or system administrators. Example: Bypass_Account_Trigger</inlineHelpText>
    <label>Bypass Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INITIALIZE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
                <default>true</default>
                <label>BEFORE_INSERT</label>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>FINALIZE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Order of field population. May be left blank if irrelevant.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerSetting__mdt/TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <label>Trigger  Setting</label>
    <pluralLabel>Trigger  Settings</pluralLabel>
</CustomObject>

force-app/commons/triggerHandlerMdt/objects/TriggerSetting__mdt/fields/BypassPermission__c.field-meta.xml
<CustomField>
    <fullName>BypassPermission__c</fullName>
    <inlineHelpText>Custom Permission API name that bypasses trigger execution. Users with this permission will skip the trigger logic. Commonly used for integration users or system administrators. Example: Bypass_Account_Trigger</inlineHelpText>
    <label>Bypass Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/commons/triggerHandler/objects/TriggerSetting__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <inlineHelpText>API Name of the SObject Type, namespace included.</inlineHelpText>
    <label>SObject Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/commons/triggerHandlerMdt/classes/MetadataTriggerSettingsCtrlTest.cls
@IsTest(IsParallel=true)
private class MetadataTriggerSettingsCtrlTest {

    private static MetadataTriggerSettingsCtrl getController() {
        TriggerSetting__mdt setting = new TriggerSetting__mdt(
            DeveloperName = 'AccountTrigger',
            Label = 'Account Trigger',
            SObjectType__c = 'Account',
            Active__c = true
        );

        MetadataTriggerSettingsCtrl.mockActions = new List<TriggerAction__mdt>{
            new TriggerAction__mdt(
                Order__c = 1,
                DeveloperName = 'Action1',
                Label = 'Action 1',
                ApexClass__c = 'MetadataTriggerHandlerTest.AccountPopulateFields',
                Operation__c = TriggerOperation.BEFORE_UPDATE.name()
            ),
            new TriggerAction__mdt(
                Order__c = 2,
                DeveloperName = 'Action2',
                Label = 'Action 2',
                ApexClass__c = 'MetadataTriggerHandlerTest.AccountValidate',
                Operation__c = TriggerOperation.BEFORE_UPDATE.name()
            ),
            new TriggerAction__mdt(
                Order__c = 3,
                DeveloperName = 'Action3',
                Label = 'Action 3',
                ApexClass__c = 'MetadataTriggerHandlerTest.InvalidAction',
                Operation__c = TriggerOperation.BEFORE_UPDATE.name(),
                BypassPermission__c = 'MetadataTriggerHandlerTestPermission'
            )
        };

        ApexPages.StandardController stdController = new ApexPages.StandardController(setting);
        MetadataTriggerSettingsCtrl controller = new MetadataTriggerSettingsCtrl(stdController);
        return controller;
    }

    @IsTest
    static void testApexOptions() {
        MetadataTriggerSettingsCtrl controller = getController();

        Test.startTest();
        List<SelectOption> classOpts = controller.classOpts;
        Test.stopTest();

        Set<String> classNames = new Set<String>();
        for (SelectOption opt : classOpts) {
            classNames.add(opt.getLabel());
        }

        Assert.isTrue(classNames.contains('MetadataTriggerHandlerTest.AccountPopulateFields'));
        Assert.isTrue(classNames.contains('MetadataTriggerHandlerTest.AccountValidate'));
        Assert.isTrue(classNames.contains('MetadataTriggerHandlerTest.AccountLinkContacts'));
        Assert.isTrue(classNames.contains('MetadataTriggerHandlerTest.AccountPreventMoreThanOneContact'));
        Assert.isTrue(classNames.contains('MetadataTriggerHandlerTest.InvalidAction (!)'));
    }

    @IsTest
    static void testCustomPermissionsOptions() {
        MetadataTriggerSettingsCtrl controller = getController();

        Test.startTest();
        List<SelectOption> permissionOpts = controller.permissionOpts;
        Test.stopTest();

        Set<String> permissionNames = new Set<String>();
        for (SelectOption opt : permissionOpts) {
            permissionNames.add(opt.getLabel());
        }

        Assert.isTrue(permissionNames.contains('MetadataTriggerHandlerTestPermission (!)'));
        for (CustomPermission customPermission : [SELECT DeveloperName, NamespacePrefix FROM CustomPermission]) {
            String name = '' + (customPermission.NamespacePrefix != null ? customPermission.NamespacePrefix + '__' : '')
                + customPermission.DeveloperName;
            Assert.isTrue(permissionNames.contains(name), 'Should contain:' + name);
        }
    }

    @IsTest
    static void testNewAction() {
        MetadataTriggerSettingsCtrl controller = getController();

        Test.startTest();
        String op = TriggerOperation.BEFORE_UPDATE.name();
        controller.selectedOp = op;
        controller.addNewAction();
        MetadataTriggerSettingsCtrl.Operation beforeUpdate = controller.getOperation(op);
        Test.stopTest();

        Assert.areEqual(4, beforeUpdate.actions.size());
        TriggerAction__mdt newAction = beforeUpdate.actions[3];
        Assert.areEqual(true, newAction.Active__c);
        Assert.areEqual(4, newAction.Order__c);
    }

    @IsTest
    static void testCancel() {
        MetadataTriggerSettingsCtrl controller = getController();

        Test.startTest();
        String op = TriggerOperation.BEFORE_UPDATE.name();
        controller.selectedOp = op;
        controller.addNewAction();
        controller.cancel();
        MetadataTriggerSettingsCtrl.Operation beforeUpdate = controller.getOperation(op);
        Test.stopTest();


        Assert.areEqual(3, beforeUpdate.actions.size());
    }

    @IsTest
    static void testDeleteAction() {
        MetadataTriggerSettingsCtrl controller = getController();

        Test.startTest();
        String op = TriggerOperation.BEFORE_UPDATE.name();
        controller.selectedOp = op;
        controller.addNewAction();

        MetadataTriggerSettingsCtrl.Operation beforeUpdate = controller.getOperation(op);
        Assert.areEqual(4, beforeUpdate.actions.size());
        TriggerAction__mdt newAction = beforeUpdate.actions[3];

        controller.selectedActionId = newAction.Id;
        controller.deleteAction();
        Test.stopTest();

        Assert.areEqual(3, beforeUpdate.actions.size());
    }

    @IsTest
    static void testSave() {
        MetadataTriggerSettingsCtrl controller = getController();

        Test.startTest();
        PageReference p = Page.MetadataTriggerSettings;
        Test.setCurrentPage(p);

        controller.selectedOp = TriggerOperation.BEFORE_UPDATE.name();
        controller.save();
        Test.stopTest();


        Assert.isFalse(ApexPages.getMessages().isEmpty());
        Assert.areEqual('Metadata cannot be deployed from within a test', ApexPages.getMessages()[0].getSummary());
    }
}