force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/TriggerAction__mdt.object-meta.xml
<CustomObject>
    <description>Configure which apex classes should be run in trigger to process records.
Apex classes should be public and implement MetadataTriggerHandler.Logic interface.</description>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Action</pluralLabel>
</CustomObject>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText>Name of public Apex Class implementing FieldDefaultRule interface.
Inner class can be referenced as well ex. &quot;AccountFieldDefaults.NameDefault&quot;, but both inner and outer class have to be public.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/commons/triggerHandlerMdt/objects/TriggerAction__mdt/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <type>TextArea</type>
</CustomField>

force-app/commons/triggerHandlerMdt/classes/TriggerCommonsTest.cls
// SPDX-License-Identifier: MIT
// Copyright 2023 Piotr Kożuchowski

@IsTest
private class TriggerCommonsTest {

    @IsTest
    static void testFieldSetter() {
        Account account = new Account(BillingCountry = 'US');

        Test.startTest();
        MetadataTriggerHandler.mockMetadata(new List<TriggerAction__mdt>{
            new TriggerAction__mdt(
                ApexClass__c = 'TriggerCommons.FieldSetter',
                Parameters__c = '{"field":"ShippingCountry","formula":"{!BillingCountry}","replaceIfSet":false}'
            )
        });

        TriggerContext ctx = new TriggerContext(TriggerOperation.BEFORE_INSERT,
            new List<Account>{account}, null);

        TriggerDispatcher.run(new MetadataTriggerHandler(), ctx);
        Test.stopTest();


        Assert.areEqual(account.BillingCountry, account.ShippingCountry);
    }
}